### ISSUE TITLE
Feature Request: Framegear URL field is too short

### ISSUE THREAD

**Issue by briandoyle81CB** [coinbase/onchainkit#319]
### Describe the solution you'd like

It should show the entire url.  Some frames depend on long urls or query params that aren't visible when testing.

**Comment by MukulKolpe** [comment]
Hey @briandoyle81CB, @Zizzamia can I work on this issue?

**Comment by Zizzamia** [comment]
@MukulKolpe all yours :)

**Comment by cnasc** [comment]
I wonder if instead of growing the URL field like in #321, it would make sense to add the URL the frame response came from the the validation results? Thinking of this for two reasons:

1. Chances are when debugging the frame, you're going to look at the validation results. If you're already focused on that part of the screen, it's a better UX to have the relevant info there.
2. I think when we expand the input itself, the layout looks a little weird

@briandoyle81CB @bansalgautam thoughts on this?

**Comment by bansalgautam** [comment]
Yeah, I think that would provide a better UX. I tried it, here is the result
![image](https://github.com/coinbase/onchainkit/assets/108223901/27c8e896-5846-455c-aa3d-a2f8706b7422)

**Comment by cnasc** [comment]
@bansalgautam nice! I would just follow the format of the other cells with the key on top then the value on the bottom but other than that LGTM

**Comment by cpcramer** [comment]
Frames have been deprecated.
